from __future__ import annotations

import os
import streamlit as st
from dotenv import load_dotenv
from src.auth import show_auth_sidebar, is_admin, is_premium, is_logged_in, gate_onboarding
from src.database import Database
from src.filters import render_header_filter

load_dotenv()


def _bootstrap_secrets_toml_from_env() -> None:
    """Write `.streamlit/secrets.toml` at startup when running on hosts
    that don't have a secrets-file UI (i.e. Railway).

    Streamlit's `st.login()` reads its OAuth config from secrets.toml's
    `[auth]` + `[auth.<provider>]` blocks — there's no env-var override
    path. When the five `STREAMLIT_AUTH_*` env vars are present, we
    materialize secrets.toml at the well-known path.

    OVERWRITES if env vars are set, regardless of any pre-existing file.
    Reason: `railway up` uploads the working dir verbatim and doesn't
    honor `.gitignore`, so a stale local secrets.toml can sneak into
    the container. When the host is configured via env, env wins.

    No-op when env vars aren't set (Streamlit Cloud / local dev path —
    those use their own secrets.toml).
    """
    redirect_uri = os.environ.get("STREAMLIT_AUTH_REDIRECT_URI", "").strip()
    cookie_secret = os.environ.get("STREAMLIT_AUTH_COOKIE_SECRET", "").strip()
    client_id = os.environ.get("STREAMLIT_AUTH_CLIENT_ID", "").strip()
    client_secret = os.environ.get("STREAMLIT_AUTH_CLIENT_SECRET", "").strip()
    metadata_url = os.environ.get(
        "STREAMLIT_AUTH_SERVER_METADATA_URL",
        "https://accounts.google.com/.well-known/openid-configuration",
    ).strip()

    if not (redirect_uri and cookie_secret and client_id and client_secret):
        return  # Not configured for this host — Streamlit will boot, login
                # just won't work until the operator sets these.

    # Quote each value with TOML's basic-string syntax. Values are JWTs /
    # URLs / hex / opaque IDs — none should contain a `"` or backslash,
    # but escape just in case.
    def _q(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    # Streamlit expects provider-specific config under `[auth.<provider>]`.
    # Hard-coding "google" matches what app.py uses (st.login("google")).
    body = (
        "# Auto-generated by app.py from STREAMLIT_AUTH_* env vars at boot.\n"
        "# Overwritten on every container start when env vars are set.\n"
        "[auth]\n"
        f"redirect_uri = {_q(redirect_uri)}\n"
        f"cookie_secret = {_q(cookie_secret)}\n"
        "\n"
        "[auth.google]\n"
        f"client_id = {_q(client_id)}\n"
        f"client_secret = {_q(client_secret)}\n"
        f"server_metadata_url = {_q(metadata_url)}\n"
    )
    os.makedirs(".streamlit", exist_ok=True)
    with open(os.path.join(".streamlit", "secrets.toml"), "w") as f:
        f.write(body)


# Run BEFORE any st.* call that touches secrets — Streamlit caches the
# parsed secrets file on first access, so writing it later wouldn't help.
_bootstrap_secrets_toml_from_env()

# Promote Streamlit Cloud secrets to env so os.getenv() works everywhere
try:
    for _k in ("SUPABASE_URL", "SUPABASE_KEY", "YOUTUBE_API_KEY"):
        if _k in st.secrets and not os.getenv(_k):
            os.environ[_k] = st.secrets[_k]
except Exception:
    pass

st.set_page_config(
    page_title="Football YouTube Tracker",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Navigation ────────────────────────────────────────────────
# Tier 0 — public (visible to everyone, including not signed in)
public_pages = [
    st.Page("views/0_Home.py", title="Home", default=True),
]

# Tier 1 — viewer (any signed-in user)
viewer_pages = [
    st.Page("views/1_Daily_Recap.py", title="Daily Recap"),
    st.Page("views/1b_Latest.py", title="Latest Videos"),
    st.Page("views/3_Season_2526.py", title="Season (25/26)"),
    st.Page("views/3b_Season_Top_Videos.py", title="Season Top"),
    st.Page("views/2_Clubs.py", title="All Channels"),
    st.Page("views/4_Top_Videos.py", title="All-Time Top"),
]

# Tier 1.7 — "Others": tangential entity types we track but don't
# blend into the main club/league views (Players, Federations,
# OtherClubs, WomenClubs). Their data is isolated by design.
other_pages = [
    st.Page("views/13_Players.py", title="Players"),
    st.Page("views/14_Federations.py", title="Federations"),
    st.Page("views/15_Other_Clubs.py", title="Other Clubs"),
    st.Page("views/17_Women.py", title="Women"),
]

# Tier 1.5 — "The Lab": experimental / analytical pages, viewer-tier
# (no invite needed). Carved out into its own sidebar family so users
# know these are exploratory features, not core data.
lab_pages = [
    st.Page("views/4b_Outliers.py", title="Outliers"),
    st.Page("views/16_Socials.py", title="Other Social"),
]

# Tier 2 — premium (promote users via User Management)
# Viewers see these with a 🔒 suffix; clicking shows an upgrade CTA.
premium_pages_unlocked = [
    st.Page("views/5_Club_Comparison.py", title="Compare"),
    st.Page("views/6_AI_Analysis.py", title="AI Analysis"),
    st.Page("views/10_Ask_Data.py", title="Ask Data"),
]
premium_pages_locked = [
    st.Page("views/5_Club_Comparison.py", title="Compare 🔒"),
    st.Page("views/6_AI_Analysis.py", title="AI Analysis 🔒"),
    st.Page("views/10_Ask_Data.py", title="Ask Data 🔒"),
]

# Tier 3 — admin only
admin_pages = [
    st.Page("views/7_Refresh_Data.py", title="Data"),
    st.Page("views/8_Channel_Management.py", title="Channel Management"),
    st.Page("views/9_User_Management.py", title="User Management"),
    st.Page("views/11_Snapshot_Debug.py", title="Snapshot Debug"),
]

nav = {"": public_pages}
if is_logged_in():
    nav[""] = public_pages + viewer_pages
    # Order: The Lab (analytical) → Others (isolated entity types) →
    # Invite-only → Admin. Lab first because it's the more interesting
    # place to land; Others is where the player/federation/etc detail lives.
    nav["The Lab"] = lab_pages
    nav["Others"] = other_pages
if is_premium():
    nav["Invite-only"] = premium_pages_unlocked
elif is_logged_in():
    nav["Invite-only"] = premium_pages_locked
if is_admin():
    nav["Admin"] = admin_pages

pg = st.navigation(nav)
show_auth_sidebar()

# Global onboarding gate: any logged-in user who hasn't completed the
# one-time profile form sees it before any page renders — including the
# public Home page which has no require_login() of its own. This makes
# sign-up flow consistent everywhere.
gate_onboarding()

# Hide Streamlit Cloud chrome (hamburger / deploy button / "Made with
# Streamlit" footer / GitHub badge / source link) for non-admin viewers
# so they get a cleaner public-facing app. Admins keep the full toolbar
# for debugging and deploys.
if not is_admin():
    st.markdown("""
        <style>
          #MainMenu {visibility: hidden !important;}
          header [data-testid="stToolbar"] {visibility: hidden !important;}
          .stDeployButton {display: none !important;}
          .stAppDeployButton {display: none !important;}
          [data-testid="stStatusWidget"] {display: none !important;}
          [data-testid="stDecoration"] {display: none !important;}
          footer {visibility: hidden !important;}
          .viewerBadge_link__qRIco,
          .viewerBadge_container__r5tak,
          .viewerBadge_button__bp24L,
          [data-testid="stAppViewerBadge"],
          ._container_gzau3_1,
          ._link_gzau3_10,
          ._profilePreview_gzau3_63 {display: none !important;}
        </style>
    """, unsafe_allow_html=True)

# ── Global header filter ──────────────────────────────────────
if st.query_params.get("view") == "feed":
    st.session_state["_feed_mode"] = True

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")

_no_filter_pages = {"Home", "Players", "Federations", "Other Clubs", "Women"}
_show_filter = getattr(pg, "title", "") not in _no_filter_pages

if SUPABASE_URL and SUPABASE_KEY:
    db = Database(SUPABASE_URL, SUPABASE_KEY)
    all_channels = db.get_all_channels()
    if all_channels:
        # Always cache the channel list so isolated pages can read it,
        # but only render the league/club filter on pages where it applies.
        st.session_state["_global_channels"] = all_channels
        if _show_filter:
            league, club = render_header_filter(all_channels)
            st.session_state["_global_league"] = league
            st.session_state["_global_club"] = club

# Removed the horizontal divider that used to sit between the global
# filter and the page title — the filter row already reads as its
# own band, the divider just added visual noise.

# ── YouTube overlay player (one per session) ─────────────────
import streamlit.components.v1 as _components
from src.analytics import yt_overlay_html
_components.html(yt_overlay_html(), height=0)

# ── Sidebar promo ────────────────────────────────────────────
with st.sidebar:
    st.markdown("---")
    st.markdown(
        """
        <div style="font-size:12px;color:#999;line-height:1.6">
            <b style="color:#FAFAFA">YTFT</b> brought to you by<br>
            <b style="color:#FAFAFA">Carlo De Marchis</b><br>
            <i>A guy with a scarf</i><br>
            <a href="https://www.linkedin.com/newsletters/a-guy-with-a-scarf-6998145822441775104/" target="_blank" style="color:#FF6B6B;text-decoration:none">📬 Newsletter</a> ·
            <a href="https://linkedin.com/in/carlodemarchis" target="_blank" style="color:#0A66C2;text-decoration:none">💼 LinkedIn</a><br>
            <a href="https://aguywithascarf.substack.com" target="_blank" style="color:#FF6719;text-decoration:none">✍️ Substack</a><br>
            <a href="https://a-guy-with-a-scarf.mykajabi.com/course" target="_blank" style="color:#F5A623;text-decoration:none">📖 Course</a> ·
            <a href="https://amzn.eu/d/09cuCSkB" target="_blank" style="color:#F5A623;text-decoration:none">📕 Book</a>
        </div>
        """,
        unsafe_allow_html=True,
    )

pg.run()
