from __future__ import annotations

import os
import streamlit as st
from dotenv import load_dotenv
from src.auth import show_auth_sidebar, is_admin, is_premium, is_logged_in, gate_onboarding
from src.database import Database
from src.filters import render_header_filter

load_dotenv()


def _bootstrap_secrets_toml_from_env() -> None:
    """Write `.streamlit/secrets.toml` at startup when running on hosts
    that don't have a secrets-file UI (i.e. Railway).

    Streamlit's `st.login()` reads its OAuth config from secrets.toml's
    `[auth]` + `[auth.<provider>]` blocks — there's no env-var override
    path. When the five `STREAMLIT_AUTH_*` env vars are present, we
    materialize secrets.toml at the well-known path.

    OVERWRITES if env vars are set, regardless of any pre-existing file.
    Reason: `railway up` uploads the working dir verbatim and doesn't
    honor `.gitignore`, so a stale local secrets.toml can sneak into
    the container. When the host is configured via env, env wins.

    No-op when env vars aren't set (Streamlit Cloud / local dev path —
    those use their own secrets.toml).
    """
    redirect_uri = os.environ.get("STREAMLIT_AUTH_REDIRECT_URI", "").strip()
    cookie_secret = os.environ.get("STREAMLIT_AUTH_COOKIE_SECRET", "").strip()
    client_id = os.environ.get("STREAMLIT_AUTH_CLIENT_ID", "").strip()
    client_secret = os.environ.get("STREAMLIT_AUTH_CLIENT_SECRET", "").strip()
    metadata_url = os.environ.get(
        "STREAMLIT_AUTH_SERVER_METADATA_URL",
        "https://accounts.google.com/.well-known/openid-configuration",
    ).strip()

    if not (redirect_uri and cookie_secret and client_id and client_secret):
        return  # Not configured for this host — Streamlit will boot, login
                # just won't work until the operator sets these.

    # Quote each value with TOML's basic-string syntax. Values are JWTs /
    # URLs / hex / opaque IDs — none should contain a `"` or backslash,
    # but escape just in case.
    def _q(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    # Streamlit expects provider-specific config under `[auth.<provider>]`.
    # Hard-coding "google" matches what app.py uses (st.login("google")).
    body = (
        "# Auto-generated by app.py from STREAMLIT_AUTH_* env vars at boot.\n"
        "# Overwritten on every container start when env vars are set.\n"
        "[auth]\n"
        f"redirect_uri = {_q(redirect_uri)}\n"
        f"cookie_secret = {_q(cookie_secret)}\n"
        "\n"
        "[auth.google]\n"
        f"client_id = {_q(client_id)}\n"
        f"client_secret = {_q(client_secret)}\n"
        f"server_metadata_url = {_q(metadata_url)}\n"
    )
    os.makedirs(".streamlit", exist_ok=True)
    with open(os.path.join(".streamlit", "secrets.toml"), "w") as f:
        f.write(body)


# Run BEFORE any st.* call that touches secrets — Streamlit caches the
# parsed secrets file on first access, so writing it later wouldn't help.
_bootstrap_secrets_toml_from_env()

# Promote Streamlit Cloud secrets to env so os.getenv() works everywhere
try:
    for _k in ("SUPABASE_URL", "SUPABASE_KEY", "YOUTUBE_API_KEY"):
        if _k in st.secrets and not os.getenv(_k):
            os.environ[_k] = st.secrets[_k]
except Exception:
    pass

st.set_page_config(
    page_title="Football YouTube Tracker",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Navigation ────────────────────────────────────────────────
# Each st.Page sets an explicit url_path so we can robustly distinguish
# pages even if two groups ever share a title (the explicit url_path
# is the stable identity, independent of the display label).

# Tier 0 — public (visible to everyone, including not signed in)
public_pages = [
    st.Page("views/0_Home.py", title="Home", url_path="home", default=True),
]

# Tier 1 — viewer (any signed-in user) — "Top 5 Leagues" group
# Season title carries the current label dynamically (`current_season_label_safe()`
# returns e.g. "25/26" today, "26/27" once the 1 Jul 2026 boundary
# passes). url_path is season-neutral so bookmarks survive the rollover.
from src.channels import current_season_label_safe as _csl
viewer_pages = [
    st.Page("views/1_Daily_Recap.py",       title="Daily Recap",       url_path="daily-recap"),
    st.Page("views/1b_Latest.py",           title="Latest Videos",     url_path="latest-videos"),
    st.Page("views/3_Season.py",            title=f"Season ({_csl()})", url_path="season"),
    st.Page("views/3b_Season_Top_Videos.py",title="Season Top",        url_path="season-top"),
    st.Page("views/2_Clubs.py",             title="All-time",          url_path="all-channels"),
    st.Page("views/4_Top_Videos.py",        title="All-Time Top",      url_path="all-time-top"),
    st.Page("views/4c_No1_Videos.py",       title="No. 1 Videos",      url_path="no1-videos"),
]

# Tier 1.7 — "Others": tangential entity types we track but don't
# blend into the main club/league views (Players, Federations,
# OtherClubs, WomenClubs). Their data is isolated by design.
other_pages = [
    st.Page("views/13_Players.py",     title="Players",     url_path="players"),
    # Federations page parked until after WC2026 — menu item removed
    # only; the view (views/14_Federations.py) and all its code are
    # left intact. Re-add this line to bring it back.
    # st.Page("views/14_Federations.py", title="Federations", url_path="federations"),
    st.Page("views/15_Other_Clubs.py", title="Other Clubs", url_path="other-clubs"),
    st.Page("views/17_Women.py",       title="Women",       url_path="women"),
]

# Tier 1.8 — FIFA World Cup 2026 sub-app. Own sidebar group so it
# reads as a distinct product surface.
wc2026_pages = [
    st.Page("views/18_WC2026.py",         title="All Channels", url_path="wc2026"),
    st.Page("views/18c_WC2026_Latest.py", title="Latest Videos", url_path="wc2026-latest"),
    st.Page("views/18b_WC2026_Trends.py", title="Trends",       url_path="wc2026-trends"),
]

# Tier 1.5 — "The Lab": experimental / analytical pages, viewer-tier
# (no invite needed). Carved out into its own sidebar family so users
# know these are exploratory features, not core data.
lab_pages = [
    st.Page("views/4b_Outliers.py",            title="Outliers",          url_path="outliers"),
    st.Page("views/16_Socials.py",             title="Other Social",      url_path="other-social"),
    st.Page("views/16b_Digital_Footprint.py",  title="Digital Footprint", url_path="digital-footprint"),
]

# Tier 2 — premium (promote users via User Management)
# Viewers see these with a 🔒 suffix; clicking shows an upgrade CTA.
premium_pages_unlocked = [
    st.Page("views/5_Club_Comparison.py", title="Compare",     url_path="compare"),
    st.Page("views/6_AI_Analysis.py",     title="AI Analysis", url_path="ai-analysis"),
    st.Page("views/10_Ask_Data.py",       title="Ask Data",    url_path="ask-data"),
]
premium_pages_locked = [
    st.Page("views/5_Club_Comparison.py", title="Compare 🔒",     url_path="compare"),
    st.Page("views/6_AI_Analysis.py",     title="AI Analysis 🔒", url_path="ai-analysis"),
    st.Page("views/10_Ask_Data.py",       title="Ask Data 🔒",    url_path="ask-data"),
]

# Tier 3 — admin only
admin_pages = [
    st.Page("views/7_Refresh_Data.py",       title="Data",                url_path="data"),
    st.Page("views/8_Channel_Management.py", title="Channel Management",  url_path="channel-mgmt"),
    st.Page("views/9_User_Management.py",    title="User Management",     url_path="user-mgmt"),
    st.Page("views/11_Snapshot_Debug.py",    title="Snapshot Debug",      url_path="snapshot-debug"),
    st.Page("views/19_Quota_Monitor.py",     title="Quota Monitor",       url_path="quota-monitor"),
]

nav = {"": public_pages}
if is_logged_in():
    # Home stays at the top with no group label; everything else lives
    # under named groups so the sidebar reads as a clear table of
    # contents.
    nav[""] = public_pages
    nav["Top 5 Leagues"] = viewer_pages
    nav["FIFA World Cup 2026"] = wc2026_pages
    nav["The Lab"] = lab_pages
    nav["Others"] = other_pages
if is_premium():
    nav["Invite-only"] = premium_pages_unlocked
elif is_logged_in():
    nav["Invite-only"] = premium_pages_locked
if is_admin():
    nav["Admin"] = admin_pages

pg = st.navigation(nav)
show_auth_sidebar()

# Global onboarding gate: any logged-in user who hasn't completed the
# one-time profile form sees it before any page renders — including the
# public Home page which has no require_login() of its own. This makes
# sign-up flow consistent everywhere.
gate_onboarding()

# Hide Streamlit Cloud chrome (hamburger / deploy button / "Made with
# Streamlit" footer / GitHub badge / source link) for non-admin viewers
# so they get a cleaner public-facing app. Admins keep the full toolbar
# for debugging and deploys.
if not is_admin():
    st.markdown("""
        <style>
          #MainMenu {visibility: hidden !important;}
          header [data-testid="stToolbar"] {visibility: hidden !important;}
          .stDeployButton {display: none !important;}
          .stAppDeployButton {display: none !important;}
          [data-testid="stStatusWidget"] {display: none !important;}
          [data-testid="stDecoration"] {display: none !important;}
          footer {visibility: hidden !important;}
          .viewerBadge_link__qRIco,
          .viewerBadge_container__r5tak,
          .viewerBadge_button__bp24L,
          [data-testid="stAppViewerBadge"],
          ._container_gzau3_1,
          ._link_gzau3_10,
          ._profilePreview_gzau3_63 {display: none !important;}
        </style>
    """, unsafe_allow_html=True)

# ── Global header filter ──────────────────────────────────────
if st.query_params.get("view") == "feed":
    st.session_state["_feed_mode"] = True

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")

# Match by URL path instead of title so pages stay correctly
# identified even if two groups ever share a display title.
_no_filter_url_paths = {
    # "" = the default page (Home) served at the root URL "/": Streamlit
    # reports url_path="" there, NOT "home", so without it the global
    # filter wrongly reappears on Home at the root. Keep both.
    "", "home", "players", "federations", "other-clubs",
    "women", "no1-videos", "wc2026", "wc2026-trends",
    "wc2026-latest", "quota-monitor",
}
_show_filter = getattr(pg, "url_path", "") not in _no_filter_url_paths

if SUPABASE_URL and SUPABASE_KEY:
    db = Database(SUPABASE_URL, SUPABASE_KEY)
    # Use the cached wrapper (5 min TTL, shared across views) so navigation
    # doesn't trigger a fresh SELECT * on the channels table every click —
    # that's a 300-400ms blocking call now that WC2026 added ~60 federation
    # + governing-body rows (~400KB payload, 223 rows total).
    from src.cached_db import get_all_channels as _cached_channels_app
    all_channels = _cached_channels_app(db)
    if all_channels:
        # Always cache the channel list so isolated pages can read it,
        # but only render the league/club filter on pages where it applies.
        st.session_state["_global_channels"] = all_channels
        if _show_filter:
            league, club = render_header_filter(all_channels)
            st.session_state["_global_league"] = league
            st.session_state["_global_club"] = club
        elif getattr(pg, "url_path", "") in (
            "wc2026", "wc2026-trends", "wc2026-latest"
        ):
            # WC2026 sub-app has its own Confederation→Team filter.
            # Rendered here (above the page title) so it sits in the
            # exact same position as the core filter; the WC2026 pages
            # read it via get_wc2026_filter(). Separate from the core
            # filter (§10 isolation) — its own session/QP keys.
            from src.wc2026_filter import render_wc2026_filter
            _wcch = [c for c in all_channels
                     if (c.get("competitions") or {}).get("wc2026")]
            if _wcch:
                render_wc2026_filter(_wcch)

# Removed the horizontal divider that used to sit between the global
# filter and the page title — the filter row already reads as its
# own band, the divider just added visual noise.

# ── YouTube overlay player (one per session) ─────────────────
import streamlit.components.v1 as _components
from src.analytics import yt_overlay_html
_components.html(yt_overlay_html(), height=0)

# ── Sidebar promo ────────────────────────────────────────────
with st.sidebar:
    st.markdown("---")
    st.markdown(
        """
        <div style="font-size:12px;color:#999;line-height:1.6">
            <b style="color:#FAFAFA">YTFT</b> brought to you by<br>
            <b style="color:#FAFAFA">Carlo De Marchis</b><br>
            <i>A guy with a scarf</i><br>
            <a href="https://www.linkedin.com/newsletters/a-guy-with-a-scarf-6998145822441775104/" target="_blank" style="color:#FF6B6B;text-decoration:none">📬 Newsletter</a> ·
            <a href="https://linkedin.com/in/carlodemarchis" target="_blank" style="color:#0A66C2;text-decoration:none">💼 LinkedIn</a><br>
            <a href="https://aguywithascarf.substack.com" target="_blank" style="color:#FF6719;text-decoration:none">✍️ Substack</a><br>
            <a href="https://a-guy-with-a-scarf.mykajabi.com/course" target="_blank" style="color:#F5A623;text-decoration:none">📖 Course</a> ·
            <a href="https://amzn.eu/d/09cuCSkB" target="_blank" style="color:#F5A623;text-decoration:none">📕 Book</a>
        </div>
        """,
        unsafe_allow_html=True,
    )

pg.run()
