#!/usr/bin/env python3
"""Materialize `.streamlit/secrets.toml` from STREAMLIT_AUTH_* env vars.

Runs as a pre-step before `streamlit run app.py` on hosts that don't
have a secrets-file UI (Railway). Streamlit's auth subsystem reads the
file at boot, so writing it from inside app.py (which only runs on
first session connect) is too late — by then Streamlit has already
decided there's no auth provider configured.

Idempotent: rewrites the file every time, takes its config from env.

Mirrors `_bootstrap_secrets_toml_from_env()` in app.py — kept there as
a fallback for any future host where pre-running this script isn't
practical.
"""
from __future__ import annotations

import os
import sys


def main() -> int:
    redirect_uri = os.environ.get("STREAMLIT_AUTH_REDIRECT_URI", "").strip()
    cookie_secret = os.environ.get("STREAMLIT_AUTH_COOKIE_SECRET", "").strip()
    client_id = os.environ.get("STREAMLIT_AUTH_CLIENT_ID", "").strip()
    client_secret = os.environ.get("STREAMLIT_AUTH_CLIENT_SECRET", "").strip()
    metadata_url = os.environ.get(
        "STREAMLIT_AUTH_SERVER_METADATA_URL",
        "https://accounts.google.com/.well-known/openid-configuration",
    ).strip()

    if not (redirect_uri and cookie_secret and client_id and client_secret):
        print("[bootstrap_secrets] STREAMLIT_AUTH_* env vars not all set — "
              "skipping (login will be unavailable)", flush=True)
        return 0  # Don't fail the boot — app can still render public pages.

    def _q(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    body = (
        "# Auto-generated by scripts/_bootstrap_secrets.py before streamlit boot.\n"
        "# Overwritten on every container start.\n"
        "[auth]\n"
        f"redirect_uri = {_q(redirect_uri)}\n"
        f"cookie_secret = {_q(cookie_secret)}\n"
        "\n"
        "[auth.google]\n"
        f"client_id = {_q(client_id)}\n"
        f"client_secret = {_q(client_secret)}\n"
        f"server_metadata_url = {_q(metadata_url)}\n"
    )
    os.makedirs(".streamlit", exist_ok=True)
    target = os.path.join(".streamlit", "secrets.toml")
    with open(target, "w") as f:
        f.write(body)
    print(f"[bootstrap_secrets] wrote {target} ({len(body)} bytes)", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
